# Generated by Django 3.1.7 on 2021-04-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=30)),
                ('phoneno', models.CharField(max_length=12)),
                ('suggesstion', models.TextField(max_length=300)),
            ],
        ),
    ]
