# Generated by Django 3.1.7 on 2021-04-11 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phoneno',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='suggesstion',
        ),
        migrations.AddField(
            model_name='contact',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
